### ISSUE TITLE
Cost in 09_convolutional_autoencoder

### ISSUE THREAD

**Issue by da-steve101** [pkmital/tensorflow_tutorials#21]
Hi,

I am new to tf/cnns etc. but in 09_convolutional_autoencoder, shouldn't the cost be against the non-noisy input ( like in 08_denoising_autoencoder ) on [line 114](https://github.com/pkmital/tensorflow_tutorials/blob/master/python/09_convolutional_autoencoder.py#L114)?

``` python
cost = tf.reduce_sum(tf.square(y - x))
```

**Comment by pkmital** [comment]
sorry, yes, fixed.
