### ISSUE TITLE
VAE costs are nan

### ISSUE THREAD

**Issue by dantkz** [pkmital/tensorflow_tutorials#23]
Hi!

First of all, thanks for the tutorials, I could pick up tensorflow really fast because of them!

I was running the variational autoencoder example (11_variational_autoencoder.py) and noticed that the reported costs are "nan". I suspect the problem is in line 77, where "tanh" can create negative values for "y" that are later fed into "log" in lines 81 and 82. I suggest changing "tanh" in line 77 to "sigmoid" (I checked and it solves the problem).

Cheers,

Daniyar

**Comment by dantkz** [comment]
Also, the convergence is much faster with only two layers in both the encoder and decoder.

**Comment by pkmital** [comment]
ty! I have updated!
