### ISSUE TITLE
Can you add an example on how to load external databases, 

### ISSUE THREAD

**Issue by anjith2006** [pkmital/tensorflow_tutorials#3]
Awesome work!
Can you add how to load external databases, 
say a custom database of images in different category

**Comment by pkmital** [comment]
I've added a class Dataset which takes inputs and outputs, mimicing the MNIST object provided by tensorflow: https://github.com/pkmital/tensorflow_tutorials/blob/master/python/libs/dataset_utils.py#L75 - I'd add an example of how to use this with data, but that requires having the data hosted somewhere, which is a pain.  I hope this is a good first step at least.
