### ISSUE TITLE
maxunpooling for convolutional autoencoder

### ISSUE THREAD

**Issue by sevamoo** [pkmital/tensorflow_tutorials#30]
Hi @pkmital 
Thanks a lot for the great collection. 
Regarding to convolutional autoencoder example, I was wondering how it would be possible to add maxpooling and maxunpoling layers? 
The problem is that I am using your code for relatively large images (e.g. 250x250) and am going to use the latent representation layer for visualization by something like T-SNE.  
Further, based on this [work](https://pdfs.semanticscholar.org/1c6d/990c80e60aa0b0059415444cdf94b3574f0f.pdf) seems having maxpooling is essential in order to have plausible filters. 

I found discussions and some solutions [here](https://github.com/tensorflow/tensorflow/issues/2169) and [here](https://github.com/EmmaBYPeng/Tensorflow-DeconvNet-Segmentation/blob/master/tests/UnpoolLayerTest.ipynb), but could not yet figure it out how to extend your code. 
Thanks a lot for any advice.

**Comment by pkmital** [comment]
This issue may help https://github.com/tensorflow/tensorflow/issues/2169 - though you can simply just use a strided convolution/"deconvolution" as this paper shows:

Springenberg, J. T., Dosovitskiy, A., Brox, T., & Riedmiller, M. (2014). Striving for Simplicity: The All Convolutional Net, 1–14. Retrieved from http://arxiv.org/abs/1412.6806

Which is what we do in the convolutional autoencoder example.
