### ISSUE TITLE
tf.nn.deconv2d ?

### ISSUE THREAD

**Issue by memoakten** [pkmital/tensorflow_tutorials#4]
Hey, I'm getting an error in the convolutional autoencoder on the line tf.nn.deconv2d

"AttributeError: 'module' object has no attribute 'deconv2d'"

Also it isn't in the docs.
https://www.tensorflow.org/versions/master/api_docs/python/nn.html

however there is tf.nn.conv2d_transpose
https://www.tensorflow.org/versions/master/api_docs/python/nn.html#conv2d_transpose

Which is said to not be an actual deconvolution but just a transpose. Perhaps the method has recently been renamed to that?

Oddly, the 0.6 docs doesn't have conv2d_transpose or deconv2d
https://www.tensorflow.org/versions/0.6.0/api_docs/python/nn.html

Perhaps they momentarily introduced deconv2d, then though it was inaccurate if it was only doing a transpose and not true deconv, and then renamed it?

I'm running HEAD as of a few days ago.

**Comment by pkmital** [comment]
Yep looks like they rename to the more appropriately named `conv2d_transpose` in the current head: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_ops.py#L44 but had `deconv2d` for 0.6.0: https://github.com/tensorflow/tensorflow/blob/0.6.0/tensorflow/python/ops/nn_ops.py#L42 - I might keep it like this until they release a new version, as most people will likely just pip install the 0.6.0 version.

**Comment by pkmital** [comment]
Or could put in a try/except... will find some time to do that unless anyone else wants to first!

**Comment by memoakten** [comment]
sure makes sense, most people will be on 0.6. leave it as is. I'll modify on my end. can send pull request.

**Comment by pkmital** [comment]
0.7.0 is out today and the merge is about to happen on tensorflow's master. Would be very happy for any PR regarding deconv if you have one, otherwise will have a look myself.

**Comment by memoakten** [comment]
Hey, sorry, can do this over the weekend if you havent' already done so. (gonna update ofxMSATensorFlow libs with 0.7 too)
